### ISSUE TITLE
Hazelcast support for ClearPass

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas-addons#54]
Clearpass currently uses a map implementation based on ehcache to store credentials. This map via ehcache is then able to replicate state in HA deployment.s

Develop the hazelcast equivalent of EhcacheBackedMap so that clearpass can also be deployed via hazelcast, in scenarios where hazelcast itself is acting as a ticket registry. This would ease deployment configurations.

**Comment by dima767** [comment]
Nothing to code here. This becomes just a matter of configuration on CP side
