### ISSUE TITLE
Failed to read schema document 'http://unicon.net/schema/cas/cas-addons.xsd',

### ISSUE THREAD

**Issue by dontrebootme** [Unicon/cas-addons#55]
org.xml.sax.SAXParseException; lineNumber: 217; columnNumber: 33; schema_reference.4: Failed to read schema document 'http://unicon.net/schema/cas/cas-addons.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not xsd:schema.

**Comment by ahs300** [comment]
It hapens the same to me. It's impossible to acces the file http://unicon.net/schema/cas/cas-addons.xsd described above. You can try to access that file on a web browser.

I'm trying to get working the 'Role Based Services Authorization' described in https://github.com/Unicon/cas-addons/wiki/Role-Based-Services-Authorization, and there is described to access http://unicon.net/schema/cas/cas-addons.xsd at WEB-INF/spring-configuration/serviceAuthorizationContext.xml.

Thanks in advance

**Comment by jtgasper3** [comment]
@ahs300: Spring doesn't necessarily read from the url to find the schema. It has some handler files that read the schema from within the CAS add-on jar file. My guess is that your pom.xml is missing a reference to the addon. As @dima767 requested of the commenter, you should share more detail.

**Comment by dima767** [comment]
Correct - the xsd is not available on some server on the internet, so no, do not try to access it from the browser. How it works - that (virtual) url is mapped to a concrete xsd file within the jar and then the schema is mapped to the Spring namespace handler that knows how to parse the custom XML elements into Spring bean definitions. 

https://github.com/Unicon/cas-addons/blob/master/src/main/resources/META-INF/spring.schemas

https://github.com/Unicon/cas-addons/blob/master/src/main/resources/META-INF/spring.handlers

All happens in a local Java process within a web application context where the Spring application context is being defined. More specifically, that mapping is made available to Spring on the classpath from cas-addons jar So it is  _key_ to have the cas-addons.jar on the classpath of your cas web archive in order for the custom schema to work.

Best,
D.

**Comment by ahs300** [comment]
First of all, thank you (@jtgasper3 and @dima767) for your quick response.

It solved the problem!!! I'm new with Maven and Spring, and I thought that including the cas-addons dependency on the pom.xml to build the CAS server was enough to generate the cas-addons.jar inside the .war file.
As you said, copying the cas-addons jar file in /opt/apache-tomcat/webapps/cas-server-webapp/WEB-INF/lib directory, the schema worked fine.

Thanks again for your quick and helpful response
