### ISSUE TITLE
principal.id is only available if initial login went to casGenericSuccess

### ISSUE THREAD

**Issue by gregskinner** [Unicon/cas-addons#63]
This addon does half of what I'd like it to do.  Some of our third party apps are setup to redirect to our CAS server, where the user logs in, and CAS redirects them back.  Unfortunately, this behavior results in the username not being captured by CAS.  I'm trying to have a role based list of applications on the casGenericSuccess page, so having the username consistently in order to do a role lookup is critical to what I'm trying to do.

I appreciate all the work done with this, and I feel like I'm so so close to having a perfect solution.  Thank you for the help.

**Comment by dima767** [comment]
Please note that this project is not officially maintained anymore, as it is based on the EOLed version of CAS.

For more options and features I would encourage you to look into CAS version `5.0.0`
